name: Check Branch - merge to master

on:
  pull_request:
    branches: [ "master" ]

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'master' && github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to master from develop."
          exit 1